version: '2.4'
services:
  nextcloud-database:
    environment:
      # MYSQL_USER: ${DATABASE_USER}
      # MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      # MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      # MYSQL_DATABASE: nextcloud

      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    build:
      context: ./services/nextcloud-database
    volumes:
      - ./.volumes/nextcloud/database:/var/lib/postgresql/data
      # - ./.volumes/nextcloud/database:/var/lib/mysql
    restart: unless-stopped
    cpu_count: 1

  nextcloud-cache:
    build:
      context: ./services/nextcloud-cache
    volumes:
      - ./.volumes/nextcloud/cache:/data
    restart: unless-stopped

  nextcloud-server:
    environment:
      # MYSQL_HOST: nextcloud-database
      # MYSQL_USER: ${DATABASE_USER}
      # MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      # MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      # MYSQL_DATABASE: nextcloud

      POSTGRES_HOST: nextcloud-database
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: nextcloud
      REDIS_HOST: nextcloud-cache
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
    build:
      context: ./services/nextcloud-server
    volumes:
      - ./.volumes/nextcloud/html:/var/www/html
      - ${DATA_PATH}:/var/www/html/data
    restart: unless-stopped

  nextcloud-static:
    build:
      context: ./services/nextcloud-static
    volumes:
      - ./.volumes/nextcloud/html:/var/www/html:ro
    ports:
      - 80:80
    restart: unless-stopped

  smb:
    environment:
      DATA_PATH_SUBFOLDER: ${DATA_PATH_SUBFOLDER}
    build:
      context: ./services/smb
    volumes:
      - ${DATA_PATH}:/media/storage
    ports:
      - 135:135/tcp
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    restart: unless-stopped
