version: '2.4'
services:
  ui:
    image: docker-clister-ui:1.0.0
    build:
      context: ./services/ui
    ports:
      - 80:80
    restart: unless-stopped

  filebrowser:
    image: docker-clister-filebrowser:1.0.0
    build:
      context: ./services/filebrowser
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${DC_VOLUMES_PATH}/filebrowser/db:/home/filebrowser/db
      - ${DC_DATA_PATH}:/home/filebrowser/data
    restart: unless-stopped

  # smb:
  #   environment:
  #     # PUID: ${PUID}
  #     # PGID: ${PGID}
  #     DATA_PATH: /media
  #   build:
  #     context: ./services/smb
  #     args:
  #       ALPINE_VERSION: ${ALPINE_VERSION}
  #   volumes:
  #     # - ./.volumes/smb:/var/lib/samba
  #     - ./.data:/media
  #   ports:
  #     - 135:135/tcp
  #     - 137:137/udp
  #     - 138:138/udp
  #     - 139:139/tcp
  #     - 445:445/tcp
  #   # user: ${PUID}:${PGID}
  #   restart: unless-stopped

  # x-mpd:
  #   environment:
  #     MPD_PORT: ${DC_MPD_PORT}
  #     DATA_PATH: /media
  #     # DATA_PATH: smb://smb/guest/Music
  #     LOG_LEVEL: ${DC_MPD_LOG_LEVEL}
  #     ALSA_DEVICE: ${DC_MPD_ALSA_DEVICE}
  #   build:
  #     context: ./services/mpd
  #     args:
  #       ALPINE_VERSION: ${ALPINE_VERSION}
  #   volumes:
  #     - ./.volumes/mpd/cache:/mpd/cache
  #     - ./.volumes/mpd/playlists:/mpd/playlists
  #     - ./.data/Music:/media
  #   devices:
  #     - /dev/snd:/dev/snd
  #   user: ${PUID}:${PGID}
  #   ports:
  #     - ${DC_MPD_PORT}:${DC_MPD_PORT}
  #   restart: unless-stopped

  # x-ympd:
  #   environment:
  #     MPD_HOST: mpd
  #     MPD_PORT: ${DC_MPD_PORT}
  #   build:
  #     context: ./services/ympd
  #     args:
  #       ALPINE_VERSION: ${ALPINE_VERSION}
  #   user: ${PUID}:${PGID}
  #   restart: unless-stopped

  # x-qbittorrent:
  #   environment:
  #     PUID: ${PUID}
  #     PGID: ${PGID}
  #     TZ: Europe/Kiev
  #     WEBUI_PORT: 80
  #   build:
  #     context: ./services/qbittorrent
  #   ports:
  #     - 6881:6881
  #     - 6881:6881/udp
  #     - 8080:8080
  #   restart: unless-stopped
