version: '2.4'
services:
  nextcloud-database:
    environment:
      # MYSQL_USER: ${DC_DATABASE_USER}
      # MYSQL_PASSWORD: ${DC_DATABASE_PASSWORD}
      # MYSQL_ROOT_PASSWORD: ${DC_DATABASE_PASSWORD}
      # MYSQL_DATABASE: nextcloud

      POSTGRES_USER: ${DC_DATABASE_USER}
      POSTGRES_PASSWORD: ${DC_DATABASE_PASSWORD}
    build:
      context: ./services/nextcloud-database
    volumes:
      # - ./.volumes/nextcloud/database:/var/lib/mysql
      - ./.volumes/nextcloud/database:/var/lib/postgresql/data
    restart: on-failure
    cpu_count: 1

  nextcloud-cache:
    build:
      context: ./services/nextcloud-cache
    volumes:
      - ./.volumes/nextcloud/cache:/data
    restart: on-failure

  nextcloud-server:
    environment:
      # MYSQL_HOST: nextcloud-database
      # MYSQL_USER: ${DC_DATABASE_USER}
      # MYSQL_PASSWORD: ${DC_DATABASE_PASSWORD}
      # MYSQL_ROOT_PASSWORD: ${DC_DATABASE_PASSWORD}
      # MYSQL_DATABASE: nextcloud

      POSTGRES_HOST: nextcloud-database
      POSTGRES_USER: ${DC_DATABASE_USER}
      POSTGRES_PASSWORD: ${DC_DATABASE_PASSWORD}
      POSTGRES_DB: nextcloud
      REDIS_HOST: nextcloud-cache
      NEXTCLOUD_ADMIN_USER: ${DC_NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${DC_NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${DC_NEXTCLOUD_TRUSTED_DOMAINS}
    build:
      context: ./services/nextcloud-server
    volumes:
      - ./.volumes/nextcloud/html:/var/www/html
      - ${DC_DATA_PATH}:/var/www/html/data
    restart: on-failure

  nextcloud-static:
    build:
      context: ./services/nextcloud-static
    volumes:
      - ./.volumes/nextcloud/html:/var/www/html:ro
    ports:
      - 80:80
    restart: on-failure

  smb:
    environment:
      DATA_PATH: /media/storage${DC_DATA_PATH_SUBFOLDER}
    build:
      context: ./services/smb
    volumes:
      - ${DC_DATA_PATH}:/media/storage
    ports:
      - 135:135/tcp
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    restart: on-failure

  mpd:
    environment:
      MPD_PORT: 6600
    build:
      context: ./services/mpd
    devices:
      - /dev/snd
    ports:
      - 6600:6600
    restart: on-failure

  ympd:
    environment:
      MPD_HOST: mpd
      MPD_PORT: 6600
    build:
      context: ./services/ympd
    ports:
      - 81:80
    restart: on-failure
